### PR TITLE
update to graffiti file

### PR DESCRIPTION
**Pull request by emkap01**
Just learning.

### CODE REVIEW

**Comment by stvnrlly** [comment]
Very nice! It looks like everything worked out here, but I'm going to suggest that you fork the [codefordc version of the repo](https://github.com/codefordc/guides) and submit this pull request there, instead of on my fork of it.

That may not be clear from the guide, so if you'd like you could submit a pull request adding a little "Make sure you're starting on https://github.com/codefordc/guides" sentence to the top of the guide.

Does that make sense?

**Comment by emkap01** [comment]
Yup, makes sense.  I will go back and give it a shot.  It's funny but when
I was doing the Python and Ruby check laid out in the guide, initially I
got an error message that the "hello world" files for each didn't exist.
It was only after digging around in the repo that I realized I was trying
to run them from the wrong directory.  Once I changed directories I was
able to run both programs no problem.

That reminds me - should I download the latest versions of Python and Ruby,
or is that unnecessary?  On my Macbook I'm running Python 2.7.6, not sure
which version I have on my desktop Mac though.  Not sure which version of
Ruby I'm running on either machine, haven't checked yet.

Eventually (if/when I ever get to the point where I'm actually coding in
Python and/or Ruby), I'd like to be able to work seamlessly between
machines if need be.  So maybe having the latest version of each on both
machines would make that easier?

BTW I also forked a copy of ANCfinder.  I know it's going to be a while
before I'm able to do anything with the copy I've got, but figured it might
be useful to experiment with as I'm learning.

**Comment by stvnrlly** [comment]
There are various different approaches to setting up a dev environment. [This](https://github.com/18F/laptop) will get you what you need and more, or you can just install things as you go along. Most people probably take the latter route, but it's often a good idea to do some reading as you go along to help keep a clean setup. What that means is avoiding installing a lot of things system-wide, as it's easy to end up with 4 different installations of Python without knowing how things got there. Homebrew will help you avoid that, and language-specific tools help manage dependencies beyond that.

For Python, it's good to have the latest versions of both 2.7 and 3. There are major differences between the two versions, so running `python2.7` on a Python 3 file can give errors. People are gradually moving to 3, but most code you'll come across is probably in 2. You can also keep a cleaner system by using `virtualenv` to avoid mixing dependencies.

For Ruby, version management can be more difficult. I recommend installing `rbenv` and using that to do the heavy lifting for you (which I've only just learned about). You may only need it down the road, but your system will be cleaner. You can also use `bundle` to manage gem dependencies. 

(I'm closing the PR, but feel free to continue to ask me questions here or on Slack.)

**Comment by stvnrlly** [comment]
(Just updated the above comment to rbenv instead of RVM, since that's actually what I use)

**Pull request closed without merging**
